
// Generated by MaixHub

#define PARAM_CLASS_NUM 2
#define PARAM_LABELS {"fire", "smoke"}
#define PARAM_ANCHOR_NUM 5
#define PARAM_ANCHORS {4.12, 2.94, 3.53, 1.31, 0.53, 0.56, 1.16, 1.13, 1.97, 2.28}
#define PARAM_MEAN 123.5
#define PARAM_STD  58.395
#define PARAM_INPUT_W 224
#define PARAM_INPUT_H 224
#define PARAM_INPUT_C 3
#define PARAM_OUTPUT_W 7
#define PARAM_OUTPUT_H 7
#define PARAM_OUTPUT_C 35

