
// Generated by MaixHub

#define PARAM_CLASS_NUM 4
#define PARAM_LABELS {"1正", "1反", "2正", "3正"}
#define PARAM_ANCHOR_NUM 5
#define PARAM_ANCHORS {1.55, 2.63, 3.48, 5.28, 2.72, 4.16, 2.42, 4.30, 2.06, 3.53}
#define PARAM_MEAN 123.5
#define PARAM_STD  58.395
#define PARAM_INPUT_W 224
#define PARAM_INPUT_H 224
#define PARAM_INPUT_C 3
#define PARAM_OUTPUT_W 7
#define PARAM_OUTPUT_H 7
#define PARAM_OUTPUT_C 45

